# -*- coding: utf-8 -*-
"""PASSWORD GENERATOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1arR1JiHk8eTf47-9Ed-HvHmL-Y2N5N_I

PROJECT NAME: Password Generator
"""

import random

letter =["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"]
numbers =["0","1","2","3","4","5","6","7","8","9"]
symbols =["!","@","#","$","%","^","&","*","(",")"]

print ("Generator your password!")
nr_letters = int(input("Number of letters you want in your password?\n"))
nr_symbols = int(input(f"Number of symbols you want in your password?\n"))
nr_numbers = int(input(f"How many numbers you want in your password?\n"))
password_list=[]

for i in range (1,nr_letters+1):
  char = random.choice(letter)
  password_list +=char

for i in range(1,nr_symbols+1):
  char = random.choice(symbols)
  password_list+=char

for i in range(1,nr_numbers+1):
  char = random.choice(numbers)
  password_list+=char

random.shuffle(password_list)

password = ""
for char in password_list:
  password += char
print (password)

print ("Here is your generated password.")