# -*- coding: utf-8 -*-
"""WHEATHER FORECAST APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17XSwnccFl59u11SdWJ2G-R4cuD46QaLr
"""

from tkinter import *
from tkinter import ttk
import requests
import json

def data_get():
  city=city_name.get()
  data = requests.get("https://api.openweathermap.org/data/2.5/weather?q="+city+"&appid=a9390f8429be0b95a8631940485add06")
  w_label1.config(text=data["weather"][0]["main"])
  wd_label1.config(text=data["weather"][0]["description"])
  temp_label1.config(text=str(int(data["main"]["temp"]-273.15)))
  per_label1.config(text=data["main"]["pressure]"])


city_name = "karachi"
data = requests.get("https://api.openweathermap.org/data/2.5/weather?q="+city_name+"&appid=a9390f8429be0b95a8631940485add06").json()
print (data)

win = Tk()
win.title("PFS Intern Weather App")
win.config(bg='blue')
win.geometry("500x570")

name_label = Label(win, text="PFS Intern Weather App", font=('arial', 25, 'bold'))
name_label.place(x=25, y=50, height=50, width=450)

city_name = StringVar()
list_names = ["sindh", "punjab", "balochistan", "kpk", "Islamabad"]
com = ttk.Combobox(win, values=list_names, font=('arial', 25, 'bold'), textvariable= city_name)
com.place(x=200, y=190, height=50, width=100)

w_label = Label(win, text="Weather Climate", font=('arial', 25, 'bold'))
w_label.place(x=25, y=260, height=50, width=210)

w_label1 = Label(win, text="t", font=('arial', 25, 'bold'))
w_label1.place(x=250, y=260, height=50, width=210)

wd_label = Label(win, text="Weather Description", font=('arial', 25, 'bold'))
wd_label.place(x=25, y=330, height=50, width=210)

wd_label1 = Label(win, text="t", font=('arial', 25, 'bold'))
wd_label1.place(x=250, y=330, height=50, width=210)

temp_label = Label(win, text="Temperature", font=('arial', 25, 'bold'))
temp_label.place(x=25, y=400, height=50, width=210)

temp_label1 = Label(win, text="t", font=('arial', 25, 'bold'))
temp_label1.place(x=250, y=400, height=50, width=210)

per_label = Label(win, text="Pressure", font=('arial', 25, 'bold'))
per_label.place(x=25, y=470, height=50, width=210)

per_label1 = Label(win, text="t", font=('arial', 25, 'bold'))
per_label1.place(x=250, y=470, height=50, width=210)

done_button = Button(win, text="Find Weather", font=('arial', 25, 'bold'), command=data_get)
done_button.place(x=25, y=250, height=50, width=450)

win.mainloop()

